name= input("Enter your name: ")
age= int(input( "enter your age: "))
address= input("enter your address: ")
print ("\nUser Information:")
print (" ")
name= input("Enter your name: ")
print( f"Age: {age}")
print( f"Address: {address}")
